# Setup
title:            bilgehanduman
tagline:          'title'
description:      'Jack of all trades, <a href="https://jekyllrb.com" target="_blank"></a> master of none. <a href=" target="_blank"></a>.'
url:              https://Purxianf.github.io
baseurl:          ''
paginate:         2

# About and contact
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
