# Setup
title:            bilgehanduman
tagline:          'title'
description:      'Jack of all trades,'
'master of none.'
url:              https://Purxianf.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Bilgehan Duman'
  url:            https://instagram.com/bilgehanduman

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
